"""Prompt templates for the BookWriter pipeline."""

from .templates import (
    SYSTEM_PREAMBLE,
    OUTLINE_INSTRUCTIONS,
    CHAPTER_INSTRUCTIONS,
    LUCIFER_CRITIQUE_INSTRUCTIONS,
    REVISION_INSTRUCTIONS,
)

__all__ = [
    "SYSTEM_PREAMBLE",
    "OUTLINE_INSTRUCTIONS",
    "CHAPTER_INSTRUCTIONS",
    "LUCIFER_CRITIQUE_INSTRUCTIONS",
    "REVISION_INSTRUCTIONS",
]
