#!/usr/bin/env python3
"""Build the Urantipedia layer inside the Obsidian vault.

Urantipedia is an encyclopedia over the Foreword + 196 papers. Each entry takes
a concept (e.g. "Consciousness") and examines it from every angle — definition,
semantic roots, facets, ramifications, implicit/hidden meanings — and maps it
into URANTiOS.

This generator does the mechanical, repeatable part so the authoring can focus
on meaning:

  obsidian/Urantipedia/
    Urantipedia — Home.md          Index of all concept entries (regenerated)
    _Concept Template.md           Blank template to copy for new concepts
    <Concept>.md                   Authored entry — created once, NEVER overwritten
    _appearances/<Concept>.md      Every occurrence across the 197 papers, linked
                                   to the exact paragraph (regenerated every run)

Each authored entry transcludes its appearances file with `![[_appearances/X]]`,
so re-running this script refreshes the harvested evidence without ever touching
what you have written. Run from the repo root:

    python3 pipeline/build_urantipedia.py
"""
from __future__ import annotations

import re
from pathlib import Path

# Reuse the vault helpers so block IDs / filenames stay identical to Papers/.
from build_obsidian_vault import REPO, block_id, load_papers, paper_filename

VAULT = REPO / "obsidian"
URANTIPEDIA = VAULT / "Urantipedia"
APPEARANCES = URANTIPEDIA / "_appearances"

# Cap how many occurrences are listed per concept so ubiquitous terms (e.g.
# "God") stay readable. The full count is always reported.
MAX_APPEARANCES = 60
SNIPPET_RADIUS = 90  # characters of context on each side of the match

# Seed concepts. The Foreword's definitional terms come first (the term-mapping
# root of the whole book), followed by the cross-cutting concepts URANTiOS is
# built on. Add more here — re-running only creates entries that don't exist.
SEED_CONCEPTS = [
    # Foreword definitional spine
    "Deity", "Divinity", "God", "Reality", "Personality",
    "Energy", "Pattern", "The Supreme Being", "The Ultimate", "The Absolute",
    "Trinity",
    # System values & cross-cutting concepts
    "Truth", "Beauty", "Goodness",
    "Consciousness", "Mind", "Spirit", "Soul", "Will",
    "Love", "Mercy", "Wisdom", "Faith", "Worship",
    "Ascension", "Evolution", "Free will",
]


def search_terms(concept: str) -> list[str]:
    """Whole-word match patterns for a concept (strip a leading article)."""
    base = re.sub(r"^(the|a|an)\s+", "", concept, flags=re.IGNORECASE).strip()
    return [base]


def find_appearances(concept: str, papers: list[dict]) -> list[dict]:
    terms = search_terms(concept)
    pattern = re.compile(
        r"\b(" + "|".join(re.escape(t) for t in terms) + r")\b", re.IGNORECASE
    )
    hits: list[dict] = []
    for paper in papers:
        note = paper_filename(paper["_index"], paper["_title"])[:-3]
        for section in paper.get("sections", []):
            for par in section.get("pars", []):
                content = (par.get("par_content") or "")
                m = pattern.search(content)
                if not m:
                    continue
                ref = par.get("par_ref", "")
                start = max(0, m.start() - SNIPPET_RADIUS)
                end = min(len(content), m.end() + SNIPPET_RADIUS)
                snippet = content[start:end].replace("\n", " ").strip()
                if start > 0:
                    snippet = "…" + snippet
                if end < len(content):
                    snippet = snippet + "…"
                hits.append(
                    {
                        "paper": paper["_index"],
                        "note": note,
                        "ref": ref,
                        "block": block_id(ref),
                        "snippet": snippet,
                        "count": len(pattern.findall(content)),
                    }
                )
    return hits


def render_appearances(concept: str, hits: list[dict]) -> str:
    total_pars = len(hits)
    total_mentions = sum(h["count"] for h in hits)
    lines: list[str] = []
    lines.append(f"%% Auto-generated by pipeline/build_urantipedia.py — do not edit by hand. %%")
    lines.append("")
    lines.append(
        f"**{total_mentions} mentions** across **{total_pars} paragraphs** "
        f"in The Urantia Book."
    )
    lines.append("")
    if not hits:
        lines.append("_No direct occurrences found. This may be an implicit concept —")
        lines.append("document it from ramifications and related terms above._")
        lines.append("")
        return "\n".join(lines)
    shown = hits[:MAX_APPEARANCES]
    for h in shown:
        loc = f"[[{h['note']}#^{h['block']}|{h['ref']}]]"
        lines.append(f"- {loc} — “{h['snippet']}”")
    if len(hits) > MAX_APPEARANCES:
        lines.append("")
        lines.append(
            f"_…and {len(hits) - MAX_APPEARANCES} more paragraphs. "
            f"Raise `MAX_APPEARANCES` in the generator to list more._"
        )
    lines.append("")
    return "\n".join(lines)


def entry_template(concept: str) -> str:
    safe = concept
    lines: list[str] = []
    lines.append("---")
    lines.append(f'concept: "{safe}"')
    lines.append("tags:")
    lines.append("  - urantipedia")
    lines.append("  - concept")
    lines.append("status: seed")
    lines.append("---")
    lines.append("")
    lines.append(f"# {safe}")
    lines.append("")
    lines.append("> [[Urantipedia — Home|↑ Urantipedia]]  ·  [[URANTiOS — Home|URANTiOS Home]]")
    lines.append("")
    lines.append("## Canonical Definition")
    lines.append("*What the Foreword and papers explicitly say this is.*")
    lines.append("")
    lines.append("## Semantic Roots & Etymology")
    lines.append("*Word origins, related forms, how the term carries meaning.*")
    lines.append("")
    lines.append("## Angles of Examination")
    lines.append("*Examine from every facet — add, remove, or rename as the concept demands.*")
    lines.append("- **Ontological** — what it *is*; its place in the reality hierarchy.")
    lines.append("- **Epistemological** — how it is known; its truth conditions.")
    lines.append("- **Personal / experiential** — how a being lives or encounters it.")
    lines.append("- **Spiritual** — its divine dimension and direction.")
    lines.append("- **Moral / value** — its relation to Truth, Beauty, Goodness.")
    lines.append("- **Cosmological** — its function in the universe of universes.")
    lines.append("- **Psychological / mind** — its mechanics in mind and personality.")
    lines.append("")
    lines.append("## Ramifications & Derived Concepts")
    lines.append("*What follows from it. Link related [[Urantipedia]] entries.*")
    lines.append("")
    lines.append("## Implicit / Hidden Meanings")
    lines.append("*What is not directly evident — the unwritten messages and connections.*")
    lines.append("")
    lines.append("## URANTiOS Digital Equivalent")
    lines.append("*Map into the OS: ontology, policy, protocol, memory, tests.*")
    lines.append("")
    lines.append("## Appearances in the Corpus")
    lines.append("*Auto-harvested — every paragraph that names this concept, linked to source.*")
    lines.append("")
    lines.append(f"![[_appearances/{safe}]]")
    lines.append("")
    lines.append("## Open Questions")
    lines.append("")
    return "\n".join(lines)


def render_home(concepts: list[str]) -> str:
    lines: list[str] = []
    lines.append("---")
    lines.append("tags:")
    lines.append("  - urantipedia")
    lines.append("  - moc")
    lines.append("---")
    lines.append("")
    lines.append("# Urantipedia — Home")
    lines.append("")
    lines.append("> [[URANTiOS — Home|↑ URANTiOS Home]]")
    lines.append("")
    lines.append("**The encyclopedia of the Foreword and the 196 papers.**")
    lines.append("")
    lines.append("> [!abstract] What Urantipedia is")
    lines.append("> Each entry takes a concept or term — *consciousness*, *personality*,")
    lines.append("> *the Supreme* — and examines it from every angle: its canonical")
    lines.append("> definition, semantic roots, facets, ramifications, and the implicit")
    lines.append("> meanings that are not directly evident. Every entry is anchored to its")
    lines.append("> real appearances across all 197 papers, linked to the exact paragraph.")
    lines.append("")
    lines.append("> [!tip] Add a concept")
    lines.append("> Copy `_Concept Template`, rename it to the concept, then add the term")
    lines.append("> to `SEED_CONCEPTS` in `pipeline/build_urantipedia.py` and re-run to")
    lines.append("> harvest its appearances.")
    lines.append("")
    lines.append("## Concepts")
    lines.append("")
    for c in sorted(concepts, key=str.lower):
        lines.append(f"- [[{c}|{c}]]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    URANTIPEDIA.mkdir(parents=True, exist_ok=True)
    # _appearances is fully regenerated; entries and the template are not.
    if APPEARANCES.exists():
        import shutil

        shutil.rmtree(APPEARANCES)
    APPEARANCES.mkdir(parents=True)

    papers = load_papers()

    created, refreshed = 0, 0
    for concept in SEED_CONCEPTS:
        hits = find_appearances(concept, papers)
        (APPEARANCES / f"{concept}.md").write_text(
            render_appearances(concept, hits), encoding="utf-8"
        )
        refreshed += 1
        entry_path = URANTIPEDIA / f"{concept}.md"
        if not entry_path.exists():
            entry_path.write_text(entry_template(concept), encoding="utf-8")
            created += 1

    (URANTIPEDIA / "_Concept Template.md").write_text(
        entry_template("Concept Template"), encoding="utf-8"
    )
    (URANTIPEDIA / "Urantipedia — Home.md").write_text(
        render_home(SEED_CONCEPTS), encoding="utf-8"
    )

    print(f"Urantipedia at: {URANTIPEDIA}")
    print(f"  Concepts: {len(SEED_CONCEPTS)}  (entries created: {created}, "
          f"appearances refreshed: {refreshed})")


if __name__ == "__main__":
    main()
